<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <PackageOutputPath>$(MSBuildProjectDirectory)\..\Nuget\output</PackageOutputPath>
        <Product>BoilerplateAvaloniaApp</Product>
        <AssemblyTitle>BoilerplateAvaloniaApp</AssemblyTitle>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <AvaloniaVersion>11.3.0</AvaloniaVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="Avalonia.Headless.NUnit" Version="$(AvaloniaVersion)" />

        <PackageVersion Include="NUnit" Version="4.2.2" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    </ItemGroup>
</Project>
