<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <PackageOutputPath>$(MSBuildProjectDirectory)\..\Nuget\output</PackageOutputPath>
        <Product>BoilerplateAvaloniaApp</Product>
        <AssemblyTitle>BoilerplateAvaloniaApp</AssemblyTitle>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <AvaloniaVersion>11.0.12</AvaloniaVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Platform)' == '' or '$(Platform)' == 'x64'">
        <PackageSuffix />
    </PropertyGroup>

    <PropertyGroup Condition="'$(Platform)' == 'ARM64'">
        <PackageSuffix>-ARM64</PackageSuffix>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="NLog" Version="4.6.2" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.10.0"/>
        <PackageVersion Include="NUnit" Version="3.13.3"/>
        <PackageVersion Include="NUnit3TestAdapter" Version="4.2.1"/>
        <PackageVersion Include="NUnit.Analyzers" Version="3.3.0"/>
        <PackageVersion Include="coverlet.collector" Version="3.1.2"/>
        <PackageVersion Include="Avalonia.Headless" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="Avalonia.Headless.NUnit" Version="$(AvaloniaVersion)" />
        <PackageVersion Include="ReactViewControl-Avalonia" Version="3.120.2" />
        <PackageVersion Include="ReactViewControl-Avalonia-ARM64" Version="3.120.2" />
        <PackageVersion Include="WebViewControl-Avalonia" Version="3.120.2" />
        <PackageVersion Include="WebViewControl-Avalonia-ARM64" Version="3.120.2" />
        <PackageVersion Include="ViewGenerator" Version="1.1.43" />
        <PackageVersion Include="ViewGeneratorCore" Version="1.0.229" />
        <PackageVersion Include="System.Reactive" Version="6.0.0" />
    </ItemGroup>

</Project>
