<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Headless.NUnit" />        
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CefGlue.Demo.Avalonia\CefGlue.Demo.Avalonia.csproj" />
    </ItemGroup>
</Project>
