<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU;ARM64</Platforms>
  </PropertyGroup>
  
  <PropertyGroup>
    <CFBundleDisplayName>CefGlueDemoAvalonia</CFBundleDisplayName>
    <CFBundleShortVersionString>DemoAvalonia</CFBundleShortVersionString>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="ReactViewControl-Avalonia$(PackageSuffix)" />
    <PackageReference Include="ViewGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ViewGeneratorCore">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="WebViewControl-Avalonia$(PackageSuffix)" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="App.xaml" />
    <AvaloniaResource Include="App.xaml" />
    <None Remove="Themes\DarkTheme.xaml" />
    <AvaloniaResource Include="Themes\DarkTheme.xaml" />
    <None Remove="Themes\LightTheme.xaml" />
    <AvaloniaResource Include="Themes\LightTheme.xaml" />
    <None Remove="Themes\BaseTheme.xaml" />
    <AvaloniaResource Include="Themes\BaseTheme.xaml" />
    <None Remove="ServerPage\ServerPageTopLevelView.xaml" />
    <None Remove="ControlTemplates\MenuItem.xaml" />
    <AvaloniaResource Include="ControlTemplates\MenuItem.xaml" />
    <None Remove="AggregatorWindow\AggregatorWindow.xaml" />
    <AvaloniaResource Include="AggregatorWindow\AggregatorWindow.xaml" />
    <None Remove="Aggregator\AggregatorView.xaml" />
    <AvaloniaResource Include="Aggregator\AggregatorView.xaml" />
  </ItemGroup>


</Project>
